package no.nav.familie.prosessering.domene

enum class Loggtype {
    FERDIG, FEILET, PLUKKET, BEHANDLER, KLAR_TIL_PLUKK, UBEHANDLET, AVVIKSHÅNDTERT, MANUELL_OPPFØLGING, KOMMENTAR, FEILET_OG_AUTOMATISK_REKJØRT
}
