name: 'Remove Old Images'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2-5 * * *'

jobs:
  remove-images:
    name: 'Remove old images job'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'no.nav.familie.prosessering-core'
          package-type: 'container'
          min-versions-to-keep: 1
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'no.nav.familie.prosessering-jdbc'
          package-type: 'container'
          min-versions-to-keep: 1
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'no.nav.familie.prosessering-jpa'
          package-type: 'container'
          min-versions-to-keep: 1
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'no.nav.familie.familie-prosessering'
          package-type: 'container'
          min-versions-to-keep: 1
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'no.nav.familie.prosessering-domene'
          package-type: 'container'
          min-versions-to-keep: 1
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'no.nav.familie.prosessering-repository'
          package-type: 'container'
          min-versions-to-keep: 1